### ISSUE TITLE
[Improvement] Automate publishing with github actions

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#172]
[HOW_TO_RELEASE.md](https://github.com/elm-tooling/elm-language-server/blob/master/HOW_TO_RELEASE.md) has these steps:

- Update the changelog in `CHANGELOG.md`
- Increase the version in `package.json`
- Run `npm install`
- Run `npm run compile`
- Push the code to github and wait for the CI
- Run `npm publish`
- Tag the new version on github

## Possible improvement

I think we can reduce it to:

- Update the changelog in `CHANGELOG.md`
- Increase the version in `package.json`
- Tag the new version on github
- Push the code to github and wait for the CI

### Deploy with github actions

If we publish automate publishing via github actions.

```yaml
name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
```

I'm using it here: https://github.com/andys8/elm-asset-webpack-loader/blob/master/.github/workflows/publish.yaml

It's based on: https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml
